name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip
          pip install -r requirements.txt
          pip install -e .[dev]
      - name: Lint
        run: |
          source .venv/bin/activate
          ruff check src tests
          black --check src tests
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest
